### ISSUE TITLE
how to paste options from another menu to this

### ISSUE THREAD

**Issue by dschaf** [ytmcgamer/FortniteCheatExample_UPDATED#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dschaf** [comment]
im trying to add a working instant reload script from sleepy.wtf source to this one how would i do it all i get is errors and more errors trying

**Comment by ThonkPT** [comment]
> 
> 
> im trying to add a working instant reload script from sleepy.wtf source to this one how would i do it all i get is errors and more errors trying

simple fix just give me the three in back of your card and your moms maiden name

**Comment by ytmcgamer** [comment]
> im trying to add a working instant reload script from sleepy.wtf source to this one how would i do it all i get is errors and more errors trying
just download this source its the same but with instant reload and that stuff https://github.com/0x420-420/COVID69-CRACK

**Comment by diligent1337** [comment]
lmfao

**Comment by ytmcgamer** [comment]
> lmfao

🤡😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂 xd
